require: 
  - rubocop-rails
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  UseCache: true
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false